- name: Prepare
  hosts: all
  tasks:
    - name: Create Raspberry Pi groups
      ansible.builtin.group:
        name: "{{ item }}"
      loop:
        - adm
        - dialout
        - cdrom
        - sudo
        - audio
        - video
        - plugdev
        - games
        - users
        - input
        - render
        - netdev
        - spi
        - i2c
        - gpio
